language: node_js
node_js:
  - "6"
  - "5"
  - "4"

sudo: false

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mail@victorquinn.com
    - GITHUB_REPO: victorquinn/dynasty
    - GIT_SOURCE: _docpress

before_install:
  - curl -O https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
  - tar xzvf dynamodb_local_latest.tar.gz
  - java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb &

script:
  - grunt test
  - ./node_modules/.bin/docpress build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"]; then ./node_modules/.bin/git-update-ghpages -e; fi
