language: node_js
node_js:
  - "6"
  - "5"
  - "4"

sudo: false

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mail@victorquinn.com
    - GITHUB_REPO: victorquinn/dynasty
    - GIT_SOURCE: _docpress

# cache:
#   directories:
#     - $HOME/dynamo-local

before_install:
  - ./install-local-dynamo.sh

script:
  - grunt test
  - ./node_modules/.bin/docpress build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"]; then ./node_modules/.bin/git-update-ghpages -e; fi
